[build]
builder = "railpack"
buildCommand = "npm run build"

[deploy]
preDeployCommand = ["bash railway/init-app.sh"]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
